#ifndef DEFAULT_NUMBER_OF_RECORDED_MESSAGES
#define DEFAULT_NUMBER_OF_RECORDED_MESSAGES 10
#endif

#ifndef RANDOM_PORT_NUMBER
#define RANDOM_PORT_NUMBER 0
#endif

#ifndef USERNAME_MAX_SIZE
#define USERNAME_MAX_SIZE 20
#endif

#ifndef GROUP_MAX_SIZE
#define GROUP_MAX_SIZE 20
#endif

#ifndef MESSAGE_MAX_SIZE
#define MESSAGE_MAX_SIZE 255
#endif

#ifndef JOIN_QUIT_STATUS_MESSAGE
#define JOIN_QUIT_STATUS_MESSAGE 3
#endif