name: C/C++ CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Instant-Messenger

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: echo 
      run: echo Success!
